#define KOHLE char
#define ALSPUTZFRAUARBEITEN KOHLE
#define DOPPEL double
#define HAUPT main
#define FÜR for
#define WÄHREND while
#define SCHALTER switch
#define FALL case
#define FALLS if
#define SONST else
#define GANZZAHL int
#define MATRIX Mat
#define RS_LADE_BILD_FARBE CV_LOAD_IMAGE_COLOR
#define CRAUS cout
#define ENDZ endl
#define BILDEINLESEN imread
#define BILDZEIGEN imshow
#define WARTETASTE waitKey
#define RECHNERSICHT RS
#define RS cv
#define ANWEISUNGSENDE ;
#define RAUS_DA <<
#define REIN_DA >>
